### ISSUE TITLE
audaspace fails to build against new ffmpeg 4.0

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#11]
Hi,

I tried to build audaspace against ffmpeg 4.0 on Mageia Cauldron but it fails to build, see the attached build log:

[audaspace-build_log.txt](https://github.com/audaspace/audaspace/files/1950377/audaspace-build_log.txt)

Regards,
David

**Comment by david-geiger** [comment]
This patch fixes build:

http://svnweb.mageia.org/packages/cauldron/audaspace/current/SOURCES/audaspace-ffmpeg-4.0.patch?view=markup&pathrev=1223536

**Comment by neXyon** [comment]
Hi David,

thanks for the fix. There's actually a lot more I'd like to fix, since quite a few function calls here are marked deprecated already. I'll do this as soon as I get the ffmpeg 4 update on my system here (currently in staging).

Cheers

**Comment by david-geiger** [comment]
You're welcome!

Now I see that blender also is not yet ported to ffmpeg 4 :(

**Comment by neXyon** [comment]
Yes, but there is already a patch submitted there as well :)

**Comment by neXyon** [comment]
Took a while, but it's fixed now and we're using the new API! Please let me know if there are any problems with it!
