### ISSUE TITLE
A new release after more than 4 years

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#13]
Hi,

Is it possible to have a new release, after more than 4 years, with all/latest fixes, please?

Latest blender 2.93.0 doesn't build anymore with system audaspace 1.3.0:

> /home/david/mgarepo/boinc-client/blender/BUILD/blender-2.93.0/source/blender/editors/sound/sound_ops.c: In function 'sound_mixdown_exec':
/home/david/mgarepo/boinc-client/blender/BUILD/blender-2.93.0/source/blender/editors/sound/sound_ops.c:381:14: error: too many arguments to function 'AUD_mixdown_per_channel'
  381 |     result = AUD_mixdown_per_channel(scene_eval->sound_scene,

Regards,
David

**Comment by neXyon** [comment]
Good idea, thanks for reminding me of my negligence of releases. Currently, there appear to be some bugs with the new output backends, I'll create a release as soon as these are resolved!

**Comment by StefanBruens** [comment]
Friendly ping ;-)

**Comment by neXyon** [comment]
Thanks for the reminder, I completely forgot about this issue! I've just released audaspace 1.4.0 :)
