### ISSUE TITLE
 Build failure on Mageia Cauldron with latest python 3.5 

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#2]
Hi Jörg,

I just tried to build audaspace-1.0 with our latest python 3.5 but without success I get these compile issues (past of full compile logs):

http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151007221405.daviddavid.valstar.9949/log/audaspace-1.0-5.mga6/build.0.20151007221502.log

Regards, 
David

**Comment by neXyon** [comment]
Hi David,

the error is that cmake can't find the python libraries:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
   Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
   (Required is at least version "3.2")


As the FindPythonLibs.cmake script is a part of cmake, it seems like 
there is something wrong with either the location of python or cmake's 
module. This should affect other projects that build with cmake and 
depend on python as well.

Regards,
Jörg

**Comment by david-geiger** [comment]
So ok, I think we must patched our current cmake like archlinux does:

https://projects.archlinux.org/svntogit/packages.git/tree/trunk/python-3.5.patch?h=packages/cmake

**Comment by neXyon** [comment]
Yeah, seems like. Does everything work with a patched cmake?

**Comment by david-geiger** [comment]
With new cmake 3.4.0-rc1 audaspace built properly again :) 

Sorry for the noise.

**Comment by neXyon** [comment]
Ok, good to know! :)
