### ISSUE TITLE
Build failure on Mageia 5 with latest 1.1 version 

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#3]
Hi Jörg,

I tried to build latest audaspace 1.1 on my local machine but I get an issue with numpy:

[ 89%] Building CXX object CMakeFiles/audaspace-py.dir/bindings/python/PySound.cpp.o
/home/david/mgarepo/audaspace/BUILD/audaspace-1.1/bindings/python/PySound.cpp:55:33: fatal error: numpy/ndarrayobject.h: No such file or directory
 #include <numpy/ndarrayobject.h>
                                 ^
compilation terminated.
CMakeFiles/audaspace-py.dir/build.make:169: recipe for target 'CMakeFiles/audaspace-py.dir/bindings/python/PySound.cpp.o' failed
make[2]: *** [CMakeFiles/audaspace-py.dir/bindings/python/PySound.cpp.o] Error 1
CMakeFiles/Makefile2:235: recipe for target 'CMakeFiles/audaspace-py.dir/all' failed
make[1]: *** [CMakeFiles/audaspace-py.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Whereas I have installed python3-numpy-devel + python3-numpy and the missing file is present on:
/usr/lib64/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h

Regards, David.

**Comment by neXyon** [comment]
Hi David,

thanks for reporting. I didn't have this problem, as numpy is available in the same include directory as python. Does the following patch solve the problem?

[cmake_numpy_patch.txt](https://github.com/audaspace/audaspace/files/13319/cmake_numpy_patch.txt)

Regards

**Comment by david-geiger** [comment]
Hi,

Nop sorry! patch doesn't work better:

-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found suitable version "3.4.3", minimum required is "3.2") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.4.3", minimum required is "3.2") 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNumPy.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:460 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/david/mgarepo/audaspace/BUILD/audaspace-1.1/build/CMakeFiles/CMakeOutput.log".
error: Bad exit status from /home/david/mgarepo/audaspace/BUILDROOT/rpm-tmp.qqDPmP (%build)

RPM build errors:
    Bad exit status from /home/david/mgarepo/audaspace/BUILDROOT/rpm-tmp.qqDPmP (%build)
error: failed!


Also same with -DNUMPY_INCLUDE_DIRS="%{python3_sitearch}/numpy/core/include" cmake option.

**Comment by neXyon** [comment]
Hi,

here is the fixed patch, which should work now: 
[cmake_numpy_patch.txt](https://github.com/audaspace/audaspace/files/13810/cmake_numpy_patch.txt)


Cheers

**Comment by david-geiger** [comment]
Hi Jörg,

Yeah! excellent! now this patch works :) and audaspace 1.1 built successfully.

-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found suitable version "3.4.3", minimum required is "3.2") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.4.3", minimum required is "3.2") 
-- Found NumPy: /usr/lib64/python3.4/site-packages/numpy/core/include

**Comment by neXyon** [comment]
Great, thanks for your help in resolving this issue!
