### ISSUE TITLE
Build failure on Mageia Cauldron with latest 1.2 version on ARM arch

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#4]
Hi Jörg,

On Mageia Cauldron we have started the port of arm arch (armv5tl) and now latest audaspace 1.2 doesn't built anymore on arm arch  whereas previous 1.1 release does, here the full compile log:

http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20160313160950.daviddavid.duvel.19015/log/audaspace-1.2-1.mga6/build.0.20160313161013.log

i586 and x86_64 built fine.

Regards,
David

**Comment by neXyon** [comment]
Hi David,

as discussed on IRC, g++ doesn't seem to fully implement the standard library on ARM and std::future does not work. I tried to cross-compile the sample on this website:

http://en.cppreference.com/w/cpp/thread/future

and get exactly the same error as in the log. I guess there is nothing much we can do, except for adding a build option to disable this part of the code. This could actually be handy in case someone wants to compile without fftw, which is also used in this part of the code.

Cheers,
Jörg

**Comment by david-geiger** [comment]
Hi Jörg,

So ok now since we have switched to ARMv7 on Mageia, std::future is now integrated on ARMv7.

You can close this bug report.

Thanks!

**Comment by neXyon** [comment]
Thanks for reporting back! I'm glad it works now.
