### ISSUE TITLE
Dave

### ISSUE THREAD

**Issue by plater** [audaspace/audaspace#5]
Audaspace 1.2 can't find ffmpeg:
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'ffmpeg'
--   package 'ffmpeg' not found
CMake Warning at CMakeLists.txt:410 (message):
  FFMPEG not found, plugin will not be built.

**Comment by neXyon** [comment]
Hmm, interesting, has ffmpeg changed on your system? Can you tell me where the include files and libraries are? Mine are here:

/usr/include/libavcodec/avcodec.h
/usr/include/libavformat/avformat.h
/usr/include/libavformat/avio.h
/usr/lib/libavcodec.so
/usr/lib/libavformat.so
/usr/lib/libavutil.so

Those are the ones that CMake is looking for.

**Comment by plater** [comment]
The include files didn't change places, when I pointed the build problem with ffmpeg 3 on the blender devel list it was fixed in extern/audaspace quickly but obviously it didn't come to your attention.
https://lists.blender.org/pipermail/bf-committers/2016-February/046743.html
I'm about to release ffmpeg3 to openSUSE:Factory and have to make sure that audaspace builds.

**Comment by neXyon** [comment]
That issue on the mailing list is a different one. There it was a function being used that is not part of ffmpeg anymore, this is not the case here. The problem here is that CMake cannot find ffmpeg. So please tell me the paths that you have on your system. Even if they didn't change.

**Comment by plater** [comment]
Sorry, jumped the gun, it's been such a long time since I first picked up the problem. I started to make a patch.
Index: cmake/FindFFMPEG.cmake
===================================================================
--- cmake/FindFFMPEG.cmake.orig
+++ cmake/FindFFMPEG.cmake
@@ -6,32 +6,32 @@
 #  FFMPEG_LIBRARIES - link these to use FFMPEG

 # Use pkg-config to get hints about paths
-#find_package(PkgConfig QUIET)
-#if(PKG_CONFIG_FOUND)
-#      pkg_check_modules(FFMPEG_PKGCONF ffmpeg)
-#endif(PKG_CONFIG_FOUND)
+find_package(PkgConfig REQUIRED)
+if(PKG_CONFIG_FOUND)
+       pkg_check_modules(FFMPEG_PKGCONF ffmpeg)
+endif(PKG_CONFIG_FOUND)

 # Include dir
 find_path(FFMPEG_INCLUDE_DIR
        NAMES libavcodec/avcodec.h libavformat/avformat.h libavformat/avio.h
-#      PATH_SUFFIXES include
-#      PATHS ${FFMPEG_PKGCONF_INCLUDE_DIRS}
+       PATH_SUFFIXES include
+       PATHS ${FFMPEG_PKGCONF_INCLUDE_DIRS}
 )

 # Libraries
 find_library(AVCODEC_LIBRARY
        NAMES avcodec
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
 )

 find_library(AVFORMAT_LIBRARY
        NAMES avformat
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
 )

 find_library(AVUTIL_LIBRARY
        NAMES avutil
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
 )

 find_package(PackageHandleStandardArgs)
Your cmake/FindFFMPEG.cmake doesn't look for avcodec, avformat and avio specifically :+1: 
audaspace> pkg-config --libs libavcodec
-lavcodec 
audaspace> pkg-config --libs libavutil
-lavutil 
audaspace> pkg-config --libs libavformat
-lavformat 
audaspace> pkg-config --cflags libavformat
-I/usr/include/ffmpeg 
audaspace> pkg-config --cflags libavcodec
-I/usr/include/ffmpeg                                                                                                                                                  audaspace> pkg-config --cflags libavutil
-I/usr/include/ffmpeg
Hope this helps, this is standard for all linux systems

**Comment by neXyon** [comment]
Can you check if this patch resolves the problem:

```
diff --git a/cmake/FindFFMPEG.cmake b/cmake/FindFFMPEG.cmake
index b88dad1..708fb52 100644
--- a/cmake/FindFFMPEG.cmake
+++ b/cmake/FindFFMPEG.cmake
@@ -6,32 +6,34 @@
 #  FFMPEG_LIBRARIES - link these to use FFMPEG
 
 # Use pkg-config to get hints about paths
-#find_package(PkgConfig QUIET)
-#if(PKG_CONFIG_FOUND)
-#      pkg_check_modules(FFMPEG_PKGCONF ffmpeg)
-#endif(PKG_CONFIG_FOUND)
+find_package(PkgConfig QUIET)
+
+if(PKG_CONFIG_FOUND)
+       pkg_check_modules(AVCODEC_PKGCONF libavcodec)
+       pkg_check_modules(AVFORMAT_PKGCONF libavformat)
+       pkg_check_modules(AVUTIL_PKGCONF libavutil)
+endif(PKG_CONFIG_FOUND)
 
 # Include dir
 find_path(FFMPEG_INCLUDE_DIR
        NAMES libavcodec/avcodec.h libavformat/avformat.h libavformat/avio.h
-#      PATH_SUFFIXES include
-#      PATHS ${FFMPEG_PKGCONF_INCLUDE_DIRS}
+       PATHS ${AVCODEC_PKGCONF_INCLUDE_DIRS} ${AVFORMAT_PKGCONF_INCLUDE_DIRS} ${AVUTIL_PKGCONF_INCLUDE_DIRS}
 )
 
 # Libraries
 find_library(AVCODEC_LIBRARY
        NAMES avcodec
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${AVCODEC_PKGCONF_LIBRARY_DIRS}
 )
 
 find_library(AVFORMAT_LIBRARY
        NAMES avformat
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${AVFORMAT_PKGCONF_LIBRARY_DIRS}
 )
 
 find_library(AVUTIL_LIBRARY
        NAMES avutil
-#      PATHS ${FFMPEG_PKGCONF_LIBRARY_DIRS}
+       PATHS ${AVUTIL_PKGCONF_LIBRARY_DIRS}
 )
 
 find_package(PackageHandleStandardArgs)
```

**Comment by plater** [comment]
Works like a dream, thanks

**Comment by neXyon** [comment]
Thanks, I committed it as well, so it will be in the next release.
