### ISSUE TITLE
Build failure on Ubuntu 14.04, version 1.2

### ISSUE THREAD

**Issue by josifovski** [audaspace/audaspace#6]
Hello,

I am having issues when building audaspace, I get undefined reference problem when linking audaconvert during build. Here is the output when I run make:

[ 68%] Building CXX object CMakeFiles/audaconvert.dir/demos/audaconvert.cpp.o
Linking CXX executable audaconvert
libaudaspace.so.1.2: undefined reference to `fftwf_free'
libaudaspace.so.1.2: undefined reference to `fftwf_malloc'
libaudaspace.so.1.2: undefined reference to `fftwf_plan_dft_c2r_1d'
libaudaspace.so.1.2: undefined reference to `fftwf_execute_dft_r2c'
libaudaspace.so.1.2: undefined reference to `fftwf_plan_dft_r2c_1d'
libaudaspace.so.1.2: undefined reference to `fftwf_set_timelimit'
libaudaspace.so.1.2: undefined reference to `fftwf_execute_dft_c2r'
libaudaspace.so.1.2: undefined reference to `fftwf_destroy_plan'
collect2: error: ld returned 1 exit status
make[2]: *** [audaconvert] Error 1
make[1]: *** [CMakeFiles/audaconvert.dir/all] Error 2
make: *** [all] Error 2

During configuration it seems to find all necessary libraries, for example the FFTW_LIBRARY is set to: "/usr/lib/libfftw.so", so i is not clear to me why it does not find the function definitions.

**Comment by neXyon** [comment]
You need libfftw3 and the the library should be /usr/lib/x86_64-linux-gnu/libfftw3f.so.3 if you're on x64.

**Comment by josifovski** [comment]
Thanks a lot, it solved my problem.
