### ISSUE TITLE
Feature request: ability to read current amplitude of sounds being played through BGE handle

### ISSUE THREAD

**Issue by gandalf3** [audaspace/audaspace#7]
I'd like to be able to get the current amplitude of sound being played through a handle,
e.g. for making real-time audio visualizations.

After looking through the [aud API docs](https://www.blender.org/api/blender_python_api_current/aud.html), I could not find access for this kind of thing, but it's possible I missed something.

Is this possible already? If not, is there any possibility of it being possible eventually?

**Comment by neXyon** [comment]
First: this is not so easy, the main problem being that the sample rate of audio is way higher than the sample rate of video, which means that if you just read a current amplitude at any time, you get pretty much a random value. Therefore what you would need to do is filter the audio signal accordingly to get some meaningful value representing the audio signal.

Second: currently it's not possible to somehow access the audio samples of a handle that is playing back. I have a design for audaspace where you could add monitoring somewhere in the signal flow graph, but no time to implement that as this would be done during a pretty much complete rewrite of audaspace.

Third: what you could do is filtering the sound and reading out the samples in parallel while playing it back using the data method of the sound: http://audaspace.github.io/bindings/sound.html#aud.Sound.data

I hope this helps and will close the issue for now as it is part of the todo list of the big rewrite.

**Comment by gandalf3** [comment]
Thanks, this helps a lot (sorry about the month-late response).

Your suggestion of downsampling and reading samples from the factory's data seems perfect, except I don't see any way of ensuring the visual "playback" of the downsampled and filtered audio stays in sync with the real audio playback.
Am I missing something?

**Comment by neXyon** [comment]
To synchronize the playback I would use the handle's [position](http://audaspace.github.io/bindings/handle.html#aud.Handle.position) and with that synchronize to the data you read. To convert from the position in seconds to the sample in your data, you just need to multiply with the sample rate you downsampled to.

**Comment by gandalf3** [comment]
Thanks, I just figured that out. I had somehow got that property mixed up with `location` (since that's what the BGE calls it)
