### ISSUE TITLE
First test blender VS system audaspace fails to build

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#8]
Hi,

I tried to compile latest blender 2.78 with system audaspace enabled (-DWITH_SYSTEM_AUDASPACE:BOOL=ON) but it fails to build, see the attached compile log:

[log.blender.txt](https://github.com/audaspace/audaspace/files/513912/log.blender.txt)

Regards,
David

**Comment by neXyon** [comment]
Hi David,

thanks for the report. I have the same problem and wonder why I didn't get it earlier actually.
Can you try to build audaspace with the attached [patch.txt](https://github.com/audaspace/audaspace/files/519301/patch.txt) and see if blender works then? If yes, I'll publish a new release with the fix.

Cheers

**Comment by david-geiger** [comment]
So tested your patch and I confirm now blender built fine with system audaspace:

-------------------------
Wrote : /home/david/mgarepo/blender/SRPMS/blender-2.78-1.1.mga6.src.rpm
Wrote : /home/david/mgarepo/blender/RPMS/x86_64/blender-2.78-1.1.mga6.x86_64.rpm
Success!
-------------------------

$ urpmq --requires blender-2.78-1.1.mga6.x86_64.rpm |grep 'auda'
libaudaspace-c.so.1.2()(64bit)
libaudaspace-py.so.1.2()(64bit)
$

Just a question: it is linked with libaudaspace-c.so.1.2 and libaudaspace-py.so.1.2 but I don't see libaudaspace.so.1.2, is this normal?

**Comment by neXyon** [comment]
Great, I'll try to get a release out soon, hopefully by the end of the week already. And yes, it is normal to only link to the C and Python API as the library itself is using C++11 which is not officially used in Blender yet, althought 2.8 will and then I can switch to use the library directly instead of the C API, at least in the Blender Game Engine. The C and Python libraries themselves depend on libaudaspace however, so it is still needed of course.

**Comment by david-geiger** [comment]
Hi Jörg,

Any news about a new release?

**Comment by neXyon** [comment]
Hi David,

sorry, it will take a bit longer, as there are some other issues that I want to fix before the release.

**Comment by neXyon** [comment]
Hi David,

just published the release! Hope everything is working fine with it. Thanks for your patience! :-)

**Comment by david-geiger** [comment]
Hi Jörg,

Blender build now against system audaspace (1.3.0) but crash at start:

$ blender
Writing: blender.crash.txt
Segfault (core dumped)
$

Attached the blender.crash.txt:
[blender.crash.txt](https://github.com/audaspace/audaspace/files/579037/blender.crash.txt)

**Comment by neXyon** [comment]
Interesting, I didn't have this bug with an older version of blender, that I had checked out and tested with. Anyway I fixed it in blender, but it won't fix the 2.78 release unfortunately.

**Comment by david-geiger** [comment]
Yes first I have tried with blender 2.78 and with your fix 817043c41e17a0fe8fcc3cf4915176df8fa3b44c , it worked fine but now with blender 2.78a and audaspace 1.3.0 it crashes.

**Comment by neXyon** [comment]
Can you try if the blender commit [e9689e1a204ee9b74fae7d0051b79649e79035f7](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blobdiff/4d0f7c320c29bcb5dcf4435a0740822d00d35493..e9689e1a204ee9b74fae7d0051b79649e79035f7:/source/blender/blenkernel/intern/sound.c) fixes this for you?

**Comment by david-geiger** [comment]
Ok I confirm that with this blender commit it doesn't crash anymore.
