### ISSUE TITLE
audaspace fails to build against gcc 7

### ISSUE THREAD

**Issue by david-geiger** [audaspace/audaspace#9]
Hi,
Since gcc 7 audaspace fails to build due to:

`/home/pterjan/rpmbuild/BUILD/audaspace-1.3.0/include/util/ThreadPool.h:94:68: error: 'bind' is not a member of 'std'
   std::shared_ptr<pkgdTask> task = std::make_shared<pkgdTask>(std::bind(std::forward<T>(t), std::forward<Args>(args)...));`

http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2017-09-06/audaspace-1.3.0-9.mga7.src.rpm/build.0.20170906231847.log

This patch fixes this FTBFS:
http://svnweb.mageia.org/packages/cauldron/audaspace/current/SOURCES/audaspace-gcc7.patch?view=markup&pathrev=1153844

Regards David

**Comment by neXyon** [comment]
Hi,

thanks for the report, it has been fixed in aa11968.

Cheers
